#loops
# 1. range(stop) generates numbers from 0 to (stop-1)
# 2. range(start, stop) generates numbers from start to (stop-1)
# 3. range(start, stop, step) jumps by a given step size (stop-1)
# All values generated by range() are integers.

print("Example 1: range(5)")
for i in range(5):
    print(i)

print("\nExample 2: range(3, 6)")
for i in range(3, 6):
    print(i)

print("\nExample 3: range(4, 10, 2)")
for i in range(4, 10, 2):
    print(i)


numbers = [50, 100, 150, 200]
for i in numbers:
  print(i)

#-----------------------------------------------------------------------------------------

#while loop

var=0
while var<20:
    print(var)
    var+=1

#------------------------------------------------------------------------------------------

#for loop

numbers=[1,2,3,4,5]
print(numbers[-2])
for i in numbers:
    print(i)

print("-------------------------------")
nums=[]
#for i in range(start,end,jump)
for i in range(21):
    nums.append(i)

print("-------------------------------")
for i in range(1,21):
    print(nums[i])

print("-------------------------------")
for i in range(1,20):
    if i==3:
        break
    else: print(i)

print("-------------------------------")
for i in range(1,5):
    if i==3:
        continue
    else: print(i)

#---------------------------------------------------------------------------------

print("-------------------------------")
#nested loops

for i in range(1,10):
    for j in range(1,5):
        print("i and j =",i,j)

print("-------------------------------")